#ifndef PRAGMA_AMIATP_LIB_H
#define PRAGMA_AMIATP_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_AMIATP_PROTOS_H
#include <clib/amiatp_protos.h>
#endif /* CLIB_AMIATP_PROTOS_H */

/*"amiatp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process defaults (after OpenLibrary only). */

#pragma amicall(AtpBase, 0x1E, AtpBaseTagsA(a0))
#if defined(__STORM__)
#pragma tagcall(AtpBase, 0x1E, AtpBaseTags(a0))
#endif /* __STORM__ */
#pragma amicall(AtpBase, 0x24, AtpError())
#pragma amicall(AtpBase, 0x2A, AtpGetErrorString(d0))

/* Tier 1 - AtpConnection (owns amihttp HttpSession + session JWTs). */

#pragma amicall(AtpBase, 0x30, NewAtpConnection())
#pragma amicall(AtpBase, 0x36, DisposeAtpConnection(a0))
#pragma amicall(AtpBase, 0x3C, SetAtpConnectionAttrsA(a0,a1))
#if defined(__STORM__)
#pragma tagcall(AtpBase, 0x3C, SetAtpConnectionAttrs(a0,a1))
#endif /* __STORM__ */
#pragma amicall(AtpBase, 0x42, AtpLogin(a0,a1,a2))
#pragma amicall(AtpBase, 0x48, AtpRefreshSession(a0))
#pragma amicall(AtpBase, 0x4E, AtpLogout(a0))
#pragma amicall(AtpBase, 0x54, AtpConnectionGetDid(a0))
#pragma amicall(AtpBase, 0x5A, AtpConnectionGetHandle(a0))
#pragma amicall(AtpBase, 0x60, AtpConnectionGetLastError(a0))

/* Tier 2 - Generic repo record CRUD (com.atproto.repo.*). */

#pragma amicall(AtpBase, 0x66, NewAtpRecord())
#pragma amicall(AtpBase, 0x6C, DisposeAtpRecord(a0))
#pragma amicall(AtpBase, 0x72, SetAtpRecordAttrsA(a0,a1))
#if defined(__STORM__)
#pragma tagcall(AtpBase, 0x72, SetAtpRecordAttrs(a0,a1))
#endif /* __STORM__ */
#pragma amicall(AtpBase, 0x78, AtpGetRecord(a0,a1))
#pragma amicall(AtpBase, 0x7E, AtpCreateRecord(a0,a1))
#pragma amicall(AtpBase, 0x84, AtpPutRecord(a0,a1))
#pragma amicall(AtpBase, 0x8A, AtpDeleteRecord(a0,a1))
#pragma amicall(AtpBase, 0x90, AtpListRecords(a0,a1,d0,a2,a3))
#pragma amicall(AtpBase, 0x96, DisposeAtpRecordList(a0))
#pragma amicall(AtpBase, 0x9C, AtpRecordListGetCount(a0))
#pragma amicall(AtpBase, 0xA2, AtpRecordListGetRecord(a0,d0))
#pragma amicall(AtpBase, 0xA8, AtpRecordGetUri(a0))
#pragma amicall(AtpBase, 0xAE, AtpRecordGetCid(a0))
#pragma amicall(AtpBase, 0xB4, AtpRecordGetString(a0,a1))

/* Tier 3 - Bluesky schema helpers (app.bsky.*). */

#pragma amicall(AtpBase, 0xBA, AtpGetTimeline(a0,d0,a1,a2))
#pragma amicall(AtpBase, 0xC0, AtpGetAuthorFeed(a0,a1,d0,a2,a3))
#pragma amicall(AtpBase, 0xC6, DisposeAtpFeed(a0))
#pragma amicall(AtpBase, 0xCC, AtpFeedGetCount(a0))
#pragma amicall(AtpBase, 0xD2, AtpFeedGetPost(a0,d0))
#pragma amicall(AtpBase, 0xD8, AtpFeedGetCursor(a0))
#pragma amicall(AtpBase, 0xDE, AtpFeedPostGetAuthorHandle(a0))
#pragma amicall(AtpBase, 0xE4, AtpFeedPostGetText(a0))
#pragma amicall(AtpBase, 0xEA, AtpFeedPostGetUri(a0))
#pragma amicall(AtpBase, 0xF0, AtpGetProfile(a0,a1,a2))
#pragma amicall(AtpBase, 0xF6, DisposeAtpProfile(a0))
#pragma amicall(AtpBase, 0xFC, AtpProfileGetHandle(a0))
#pragma amicall(AtpBase, 0x102, AtpProfileGetDisplayName(a0))
#pragma amicall(AtpBase, 0x108, AtpProfileGetDescription(a0))
#pragma amicall(AtpBase, 0x10E, AtpCreatePost(a0,a1,a2,d0))
#pragma amicall(AtpBase, 0x114, AtpResolveHandle(a0,a1,a2,d0))
#pragma amicall(AtpBase, 0x11A, AtpFeedPostGetAvatarUrl(a0))
#pragma amicall(AtpBase, 0x120, AtpFeedPostGetImageCount(a0))
#pragma amicall(AtpBase, 0x126, AtpFeedPostGetImageUrl(a0,d0))
#pragma amicall(AtpBase, 0x12C, AtpDownloadUrl(a0,a1,a2))

#endif /* PRAGMA_AMIATP_LIB_H */
