#ifndef INLINE_AMIATP_PROTOS_H
#define INLINE_AMIATP_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"amiatp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process defaults (after OpenLibrary only). */

LONG __AtpBaseTagsA(__reg("a6") void *, __reg("a0") struct TagItem *tags)="\tjsr\t-30(a6)";
#define AtpBaseTagsA(tags) __AtpBaseTagsA(AtpBase, (tags))

LONG __AtpBaseTags(__reg("a6") void *, ...)="\tmove.l\ta0,-(a7)\n\tlea\t4(a7),a0\n\tjsr\t-30(a6)\n\tmovea.l\t(a7)+,a0";
#define AtpBaseTags(...) __AtpBaseTags(AtpBase, __VA_ARGS__)

LONG __AtpError(__reg("a6") void *)="\tjsr\t-36(a6)";
#define AtpError() __AtpError(AtpBase)

STRPTR __AtpGetErrorString(__reg("a6") void *, __reg("d0") LONG code)="\tjsr\t-42(a6)";
#define AtpGetErrorString(code) __AtpGetErrorString(AtpBase, (code))


/* Tier 1 - AtpConnection (owns amihttp HttpSession + session JWTs). */

struct AtpConnection *__NewAtpConnection(__reg("a6") void *)="\tjsr\t-48(a6)";
#define NewAtpConnection() __NewAtpConnection(AtpBase)

void __DisposeAtpConnection(__reg("a6") void *, __reg("a0") struct AtpConnection *conn)="\tjsr\t-54(a6)";
#define DisposeAtpConnection(conn) __DisposeAtpConnection(AtpBase, (conn))

LONG __SetAtpConnectionAttrsA(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") struct TagItem *tags)="\tjsr\t-60(a6)";
#define SetAtpConnectionAttrsA(conn, tags) __SetAtpConnectionAttrsA(AtpBase, (conn), (tags))

LONG __SetAtpConnectionAttrs(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-60(a6)\n\tmovea.l\t(a7)+,a1";
#define SetAtpConnectionAttrs(conn, ...) __SetAtpConnectionAttrs(AtpBase, (conn), __VA_ARGS__)

LONG __AtpLogin(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR identifier, __reg("a2") STRPTR password)="\tjsr\t-66(a6)";
#define AtpLogin(conn, identifier, password) __AtpLogin(AtpBase, (conn), (identifier), (password))

LONG __AtpRefreshSession(__reg("a6") void *, __reg("a0") struct AtpConnection *conn)="\tjsr\t-72(a6)";
#define AtpRefreshSession(conn) __AtpRefreshSession(AtpBase, (conn))

LONG __AtpLogout(__reg("a6") void *, __reg("a0") struct AtpConnection *conn)="\tjsr\t-78(a6)";
#define AtpLogout(conn) __AtpLogout(AtpBase, (conn))

STRPTR __AtpConnectionGetDid(__reg("a6") void *, __reg("a0") struct AtpConnection *conn)="\tjsr\t-84(a6)";
#define AtpConnectionGetDid(conn) __AtpConnectionGetDid(AtpBase, (conn))

STRPTR __AtpConnectionGetHandle(__reg("a6") void *, __reg("a0") struct AtpConnection *conn)="\tjsr\t-90(a6)";
#define AtpConnectionGetHandle(conn) __AtpConnectionGetHandle(AtpBase, (conn))

LONG __AtpConnectionGetLastError(__reg("a6") void *, __reg("a0") struct AtpConnection *conn)="\tjsr\t-96(a6)";
#define AtpConnectionGetLastError(conn) __AtpConnectionGetLastError(AtpBase, (conn))


/* Tier 2 - Generic repo record CRUD (com.atproto.repo.*). */

struct AtpRecord *__NewAtpRecord(__reg("a6") void *)="\tjsr\t-102(a6)";
#define NewAtpRecord() __NewAtpRecord(AtpBase)

void __DisposeAtpRecord(__reg("a6") void *, __reg("a0") struct AtpRecord *rec)="\tjsr\t-108(a6)";
#define DisposeAtpRecord(rec) __DisposeAtpRecord(AtpBase, (rec))

LONG __SetAtpRecordAttrsA(__reg("a6") void *, __reg("a0") struct AtpRecord *rec, __reg("a1") struct TagItem *tags)="\tjsr\t-114(a6)";
#define SetAtpRecordAttrsA(rec, tags) __SetAtpRecordAttrsA(AtpBase, (rec), (tags))

LONG __SetAtpRecordAttrs(__reg("a6") void *, __reg("a0") struct AtpRecord *rec, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-114(a6)\n\tmovea.l\t(a7)+,a1";
#define SetAtpRecordAttrs(rec, ...) __SetAtpRecordAttrs(AtpBase, (rec), __VA_ARGS__)

LONG __AtpGetRecord(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") struct AtpRecord *rec)="\tjsr\t-120(a6)";
#define AtpGetRecord(conn, rec) __AtpGetRecord(AtpBase, (conn), (rec))

LONG __AtpCreateRecord(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") struct AtpRecord *rec)="\tjsr\t-126(a6)";
#define AtpCreateRecord(conn, rec) __AtpCreateRecord(AtpBase, (conn), (rec))

LONG __AtpPutRecord(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") struct AtpRecord *rec)="\tjsr\t-132(a6)";
#define AtpPutRecord(conn, rec) __AtpPutRecord(AtpBase, (conn), (rec))

LONG __AtpDeleteRecord(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") struct AtpRecord *rec)="\tjsr\t-138(a6)";
#define AtpDeleteRecord(conn, rec) __AtpDeleteRecord(AtpBase, (conn), (rec))

LONG __AtpListRecords(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR collection, __reg("d0") ULONG limit, __reg("a2") STRPTR cursor, __reg("a3") struct AtpRecordList **out_list)="\tjsr\t-144(a6)";
#define AtpListRecords(conn, collection, limit, cursor, out_list) __AtpListRecords(AtpBase, (conn), (collection), (limit), (cursor), (out_list))

void __DisposeAtpRecordList(__reg("a6") void *, __reg("a0") struct AtpRecordList *list)="\tjsr\t-150(a6)";
#define DisposeAtpRecordList(list) __DisposeAtpRecordList(AtpBase, (list))

ULONG __AtpRecordListGetCount(__reg("a6") void *, __reg("a0") struct AtpRecordList *list)="\tjsr\t-156(a6)";
#define AtpRecordListGetCount(list) __AtpRecordListGetCount(AtpBase, (list))

struct AtpRecord *__AtpRecordListGetRecord(__reg("a6") void *, __reg("a0") struct AtpRecordList *list, __reg("d0") ULONG index)="\tjsr\t-162(a6)";
#define AtpRecordListGetRecord(list, index) __AtpRecordListGetRecord(AtpBase, (list), (index))

STRPTR __AtpRecordGetUri(__reg("a6") void *, __reg("a0") struct AtpRecord *rec)="\tjsr\t-168(a6)";
#define AtpRecordGetUri(rec) __AtpRecordGetUri(AtpBase, (rec))

STRPTR __AtpRecordGetCid(__reg("a6") void *, __reg("a0") struct AtpRecord *rec)="\tjsr\t-174(a6)";
#define AtpRecordGetCid(rec) __AtpRecordGetCid(AtpBase, (rec))

STRPTR __AtpRecordGetString(__reg("a6") void *, __reg("a0") struct AtpRecord *rec, __reg("a1") STRPTR key)="\tjsr\t-180(a6)";
#define AtpRecordGetString(rec, key) __AtpRecordGetString(AtpBase, (rec), (key))


/* Tier 3 - Bluesky schema helpers (app.bsky.*). */

LONG __AtpGetTimeline(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("d0") ULONG limit, __reg("a1") STRPTR cursor, __reg("a2") struct AtpFeed **out_feed)="\tjsr\t-186(a6)";
#define AtpGetTimeline(conn, limit, cursor, out_feed) __AtpGetTimeline(AtpBase, (conn), (limit), (cursor), (out_feed))

LONG __AtpGetAuthorFeed(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR actor, __reg("d0") ULONG limit, __reg("a2") STRPTR cursor, __reg("a3") struct AtpFeed **out_feed)="\tjsr\t-192(a6)";
#define AtpGetAuthorFeed(conn, actor, limit, cursor, out_feed) __AtpGetAuthorFeed(AtpBase, (conn), (actor), (limit), (cursor), (out_feed))

void __DisposeAtpFeed(__reg("a6") void *, __reg("a0") struct AtpFeed *feed)="\tjsr\t-198(a6)";
#define DisposeAtpFeed(feed) __DisposeAtpFeed(AtpBase, (feed))

ULONG __AtpFeedGetCount(__reg("a6") void *, __reg("a0") struct AtpFeed *feed)="\tjsr\t-204(a6)";
#define AtpFeedGetCount(feed) __AtpFeedGetCount(AtpBase, (feed))

struct AtpFeedPost *__AtpFeedGetPost(__reg("a6") void *, __reg("a0") struct AtpFeed *feed, __reg("d0") ULONG index)="\tjsr\t-210(a6)";
#define AtpFeedGetPost(feed, index) __AtpFeedGetPost(AtpBase, (feed), (index))

STRPTR __AtpFeedGetCursor(__reg("a6") void *, __reg("a0") struct AtpFeed *feed)="\tjsr\t-216(a6)";
#define AtpFeedGetCursor(feed) __AtpFeedGetCursor(AtpBase, (feed))

STRPTR __AtpFeedPostGetAuthorHandle(__reg("a6") void *, __reg("a0") struct AtpFeedPost *post)="\tjsr\t-222(a6)";
#define AtpFeedPostGetAuthorHandle(post) __AtpFeedPostGetAuthorHandle(AtpBase, (post))

STRPTR __AtpFeedPostGetText(__reg("a6") void *, __reg("a0") struct AtpFeedPost *post)="\tjsr\t-228(a6)";
#define AtpFeedPostGetText(post) __AtpFeedPostGetText(AtpBase, (post))

STRPTR __AtpFeedPostGetUri(__reg("a6") void *, __reg("a0") struct AtpFeedPost *post)="\tjsr\t-234(a6)";
#define AtpFeedPostGetUri(post) __AtpFeedPostGetUri(AtpBase, (post))

LONG __AtpGetProfile(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR actor, __reg("a2") struct AtpProfile **out_profile)="\tjsr\t-240(a6)";
#define AtpGetProfile(conn, actor, out_profile) __AtpGetProfile(AtpBase, (conn), (actor), (out_profile))

void __DisposeAtpProfile(__reg("a6") void *, __reg("a0") struct AtpProfile *profile)="\tjsr\t-246(a6)";
#define DisposeAtpProfile(profile) __DisposeAtpProfile(AtpBase, (profile))

STRPTR __AtpProfileGetHandle(__reg("a6") void *, __reg("a0") struct AtpProfile *profile)="\tjsr\t-252(a6)";
#define AtpProfileGetHandle(profile) __AtpProfileGetHandle(AtpBase, (profile))

STRPTR __AtpProfileGetDisplayName(__reg("a6") void *, __reg("a0") struct AtpProfile *profile)="\tjsr\t-258(a6)";
#define AtpProfileGetDisplayName(profile) __AtpProfileGetDisplayName(AtpBase, (profile))

STRPTR __AtpProfileGetDescription(__reg("a6") void *, __reg("a0") struct AtpProfile *profile)="\tjsr\t-264(a6)";
#define AtpProfileGetDescription(profile) __AtpProfileGetDescription(AtpBase, (profile))

LONG __AtpCreatePost(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR text, __reg("a2") STRPTR uri_buf, __reg("d0") ULONG uri_buflen)="\tjsr\t-270(a6)";
#define AtpCreatePost(conn, text, uri_buf, uri_buflen) __AtpCreatePost(AtpBase, (conn), (text), (uri_buf), (uri_buflen))

LONG __AtpResolveHandle(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR handle, __reg("a2") STRPTR did_buf, __reg("d0") ULONG did_buflen)="\tjsr\t-276(a6)";
#define AtpResolveHandle(conn, handle, did_buf, did_buflen) __AtpResolveHandle(AtpBase, (conn), (handle), (did_buf), (did_buflen))

STRPTR __AtpFeedPostGetAvatarUrl(__reg("a6") void *, __reg("a0") struct AtpFeedPost *post)="\tjsr\t-282(a6)";
#define AtpFeedPostGetAvatarUrl(post) __AtpFeedPostGetAvatarUrl(AtpBase, (post))

ULONG __AtpFeedPostGetImageCount(__reg("a6") void *, __reg("a0") struct AtpFeedPost *post)="\tjsr\t-288(a6)";
#define AtpFeedPostGetImageCount(post) __AtpFeedPostGetImageCount(AtpBase, (post))

STRPTR __AtpFeedPostGetImageUrl(__reg("a6") void *, __reg("a0") struct AtpFeedPost *post, __reg("d0") ULONG index)="\tjsr\t-294(a6)";
#define AtpFeedPostGetImageUrl(post, index) __AtpFeedPostGetImageUrl(AtpBase, (post), (index))

LONG __AtpDownloadUrl(__reg("a6") void *, __reg("a0") struct AtpConnection *conn, __reg("a1") STRPTR url, __reg("a2") STRPTR path)="\tjsr\t-300(a6)";
#define AtpDownloadUrl(conn, url, path) __AtpDownloadUrl(AtpBase, (conn), (url), (path))


#endif /* INLINE_AMIATP_PROTOS_H */
