/*
 * SPDX-License-Identifier: BSD-2-Clause
 * Copyright 2026 amigazen project
 *
 * amiatp.h - proto/pragma dispatcher for amiatp.library callers
 *
 * Generated by LibDescConverter from an sfd file; variadic tag wrappers
 * are maintained for SDK publication (same pattern as proto/amihttp.h).
 */

#ifndef PROTO_AMIATP_H
#define PROTO_AMIATP_H

#include <clib/amiatp_protos.h>

#ifndef _NO_INLINE

#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_AMIATP_PRAGMAS_H
#include <pragmas/amiatp_pragmas.h>
#endif /* PRAGMAS_AMIATP_PRAGMAS_H */

#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_AMIATP_LIB_H
#include <pragma/amiatp_lib.h>
#endif /* PRAGMA_AMIATP_LIB_H */

#elif defined(__VBCC__)

#ifndef INLINE_AMIATP_PROTOS_H
#include <inline/amiatp_protos.h>
#endif /* INLINE_AMIATP_PROTOS_H */

#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_AMIATP_H
#include <inline/amiatp.h>
#endif /* INLINE_AMIATP_H */
#else
#include <clib/amiatp_protos.h>
#endif /* mc68000 */

#endif /* compiler */

#endif /* _NO_INLINE */

#ifndef __NOLIBBASE__
  extern struct Library *
# ifdef __CONSTLIBBASEDECL__
   __CONSTLIBBASEDECL__
# endif /* __CONSTLIBBASEDECL__ */
  AtpBase;
#endif /* __NOLIBBASE__ */

/****************************************************************************/
/* Variadic tag wrappers (SetXxxAttrs / BaseTags style)                     */
/****************************************************************************/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_AMIATP_H
#include <libraries/amiatp.h>
#endif

#ifndef ATP_VARARGS_DEFINED
#define ATP_VARARGS_DEFINED 1

static LONG AtpBaseTags(Tag tag1, ...)
{
    return AtpBaseTagList((struct TagItem *)&tag1);
}

static LONG SetAtpConnectionAttrs(struct AtpConnection *conn, Tag tag1, ...)
{
    return SetAtpConnectionAttrsA(conn, (struct TagItem *)&tag1);
}

static LONG SetAtpRecordAttrs(struct AtpRecord *rec, Tag tag1, ...)
{
    return SetAtpRecordAttrsA(rec, (struct TagItem *)&tag1);
}

#endif /* ATP_VARARGS_DEFINED */

#endif /* PROTO_AMIATP_H */
