#ifndef PROTO_AMIATP_H
#define PROTO_AMIATP_H

/*
** 'C' prototype and compiler specific header file combo
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/amiatp_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * AtpBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_AMIATP_PRAGMAS_H
#include <pragmas/amiatp_pragmas.h>
#endif /* PRAGMAS_AMIATP_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_AMIATP_LIB_H
#include <pragma/amiatp_lib.h>
#endif /* PRAGMA_AMIATP_LIB_H */

#elif defined(__VBCC__)

#include <clib/amiatp_protos.h>

#ifndef INLINE_AMIATP_PROTOS_H
#include <inline/amiatp_protos.h>
#endif /* INLINE_AMIATP_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_AMIATP_H
#include <inline/amiatp.h>
#endif /* INLINE_AMIATP_H */
#else
#include <clib/amiatp_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/amiatp_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_AMIATP_H */
