#ifndef INLINE_AMIATP_H
#define INLINE_AMIATP_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"amiatp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process defaults (after OpenLibrary only). */

#define AtpBaseTagList(tags)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct TagItem *p0 __asm("a0") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpError()    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpGetErrorString(code)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register LONG p0 __asm("d0") = (code);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 1 - AtpConnection (owns amihttp HttpSession + session JWTs). */

#define NewAtpConnection()    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeAtpConnection(conn)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetAtpConnectionAttrsA(conn, tags)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpLogin(conn, identifier, password)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (identifier);   \
	register STRPTR p2 __asm("a2") = (password);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpRefreshSession(conn)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpLogout(conn)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpConnectionGetDid(conn)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpConnectionGetHandle(conn)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-90:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpConnectionGetLastError(conn)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 2 - Generic repo record CRUD (com.atproto.repo.*). */

#define NewAtpRecord()    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeAtpRecord(rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecord *p0 __asm("a0") = (rec);   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetAtpRecordAttrsA(rec, tags)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecord *p0 __asm("a0") = (rec);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpGetRecord(conn, rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register struct AtpRecord *p1 __asm("a1") = (rec);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpCreateRecord(conn, rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register struct AtpRecord *p1 __asm("a1") = (rec);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpPutRecord(conn, rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register struct AtpRecord *p1 __asm("a1") = (rec);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpDeleteRecord(conn, rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register struct AtpRecord *p1 __asm("a1") = (rec);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpListRecords(conn, collection, limit, cursor, out_list)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (collection);   \
	register ULONG p2 __asm("d0") = (limit);   \
	register STRPTR p3 __asm("a2") = (cursor);   \
	register struct AtpRecordList **p4 __asm("a3") = (out_list);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-144:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3), "r"(p4) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeAtpRecordList(list)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecordList *p0 __asm("a0") = (list);   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define AtpRecordListGetCount(list)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecordList *p0 __asm("a0") = (list);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-156:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpRecordListGetRecord(list, index)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecordList *p0 __asm("a0") = (list);   \
	register ULONG p1 __asm("d0") = (index);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-162:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpRecordGetUri(rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecord *p0 __asm("a0") = (rec);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-168:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpRecordGetCid(rec)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecord *p0 __asm("a0") = (rec);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-174:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpRecordGetString(rec, key)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpRecord *p0 __asm("a0") = (rec);   \
	register STRPTR p1 __asm("a1") = (key);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-180:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 3 - Bluesky schema helpers (app.bsky.*). */

#define AtpGetTimeline(conn, limit, cursor, out_feed)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register ULONG p1 __asm("d0") = (limit);   \
	register STRPTR p2 __asm("a1") = (cursor);   \
	register struct AtpFeed **p3 __asm("a2") = (out_feed);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-186:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpGetAuthorFeed(conn, actor, limit, cursor, out_feed)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (actor);   \
	register ULONG p2 __asm("d0") = (limit);   \
	register STRPTR p3 __asm("a2") = (cursor);   \
	register struct AtpFeed **p4 __asm("a3") = (out_feed);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-192:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3), "r"(p4) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeAtpFeed(feed)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeed *p0 __asm("a0") = (feed);   \
	__asm volatile ("jsr a6@(-198:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define AtpFeedGetCount(feed)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeed *p0 __asm("a0") = (feed);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-204:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedGetPost(feed, index)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeed *p0 __asm("a0") = (feed);   \
	register ULONG p1 __asm("d0") = (index);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-210:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedGetCursor(feed)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeed *p0 __asm("a0") = (feed);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-216:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedPostGetAuthorHandle(post)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeedPost *p0 __asm("a0") = (post);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-222:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedPostGetText(post)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeedPost *p0 __asm("a0") = (post);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-228:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedPostGetUri(post)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeedPost *p0 __asm("a0") = (post);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-234:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpGetProfile(conn, actor, out_profile)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (actor);   \
	register struct AtpProfile **p2 __asm("a2") = (out_profile);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-240:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeAtpProfile(profile)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpProfile *p0 __asm("a0") = (profile);   \
	__asm volatile ("jsr a6@(-246:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define AtpProfileGetHandle(profile)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpProfile *p0 __asm("a0") = (profile);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-252:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpProfileGetDisplayName(profile)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpProfile *p0 __asm("a0") = (profile);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-258:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpProfileGetDescription(profile)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpProfile *p0 __asm("a0") = (profile);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-264:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpCreatePost(conn, text, uri_buf, uri_buflen)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (text);   \
	register STRPTR p2 __asm("a2") = (uri_buf);   \
	register ULONG p3 __asm("d0") = (uri_buflen);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-270:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpResolveHandle(conn, handle, did_buf, did_buflen)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (handle);   \
	register STRPTR p2 __asm("a2") = (did_buf);   \
	register ULONG p3 __asm("d0") = (did_buflen);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-276:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedPostGetAvatarUrl(post)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeedPost *p0 __asm("a0") = (post);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-282:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedPostGetImageCount(post)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeedPost *p0 __asm("a0") = (post);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-288:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpFeedPostGetImageUrl(post, index)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpFeedPost *p0 __asm("a0") = (post);   \
	register ULONG p1 __asm("d0") = (index);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-294:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AtpDownloadUrl(conn, url, path)    \
({  \
	register void *b __asm("a6") = AtpBase;  \
	register struct AtpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (url);   \
	register STRPTR p2 __asm("a2") = (path);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-300:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


#endif /* INLINE_AMIATP_H */
